2018-08-02 10:51:12,685 ERROR :Exception on /index [GET] [in /usr/lib/python2.7/site-packages/flask/app.py :1560 ] 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/aaron/MyPython/MyFlask/microblog/app/routes.py", line 34, in index
    prev_url = prev_url)
UnboundLocalError: local variable 'prev_url' referenced before assignment
2018-08-02 10:54:57,287 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 10:58:11,008 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 11:04:33,223 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 11:05:17,659 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 11:05:33,251 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 11:16:51,424 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 11:17:07,125 ERROR :Exception on /user/Guang Mujun [GET] [in /usr/lib/python2.7/site-packages/flask/app.py :1560 ] 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/aaron/MyPython/MyFlask/microblog/app/routes.py", line 95, in user
    if has_next else None
NameError: global name 'has_next' is not defined
2018-08-02 11:17:40,368 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 11:18:21,246 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 12:11:43,642 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 14:59:58,027 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :30 ] 
2018-08-02 16:19:34,866 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :32 ] 
2018-08-02 16:19:43,917 ERROR :Exception on /login [GET] [in /usr/lib/python2.7/site-packages/flask/app.py :1560 ] 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aaron/MyPython/MyFlask/microblog/app/routes.py", line 66, in login
    return render_template('login.html' , title = 'Sign In' , form =form )
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaron/MyPython/MyFlask/microblog/app/templates/login.html", line 18, in template
    {% block app_content %}
TemplateAssertionError: block 'app_content' defined twice
2018-08-02 16:20:34,073 INFO :Microblog startup ---- Guang Mujun [in /home/aaron/MyPython/MyFlask/microblog/app/__init__.py :32 ] 
2018-08-02 16:20:38,800 ERROR :Exception on /login [GET] [in /usr/lib/python2.7/site-packages/flask/app.py :1560 ] 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aaron/MyPython/MyFlask/microblog/app/routes.py", line 66, in login
    return render_template('login.html' , title = 'Sign In' , form =form )
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaron/MyPython/MyFlask/microblog/app/templates/login.html", line 3, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/aaron/MyPython/MyFlask/microblog/app/templates/base.html", line 2, in top-level template code
    {%  extends 'bootstrap/base.html' %}
  File "/usr/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/usr/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/aaron/MyPython/MyFlask/microblog/app/templates/base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/aaron/MyPython/MyFlask/microblog/app/templates/login.html", line 14, in block "app_content"
    <p>Forgot Your Password?<a href="{{ url_for('reset_password_request') }}">Click to Reset It</a></p>
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
